import { BaseCommand } from '@adonisjs/core/ace'
import { existsSync, readFileSync, unlinkSync } from 'node:fs'

export default class EraseBlueprint extends BaseCommand {
  static commandName = 'blueprint:erase'
  static description = 'Erase the files generated by the last blueprint:build'

  async run() {
    const manifestPath = this.app.makePath('.blueprint_manifest.json')

    if (!existsSync(manifestPath)) {
      this.logger.error('Manifest file not found. Nothing to erase.')
      return
    }

    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
    const files: string[] = manifest.files || []

    for (const file of files) {
      if (existsSync(file)) {
        unlinkSync(file)
        this.logger.action(`deleted ${file}`).succeeded()
      }
    }

    unlinkSync(manifestPath)
    this.logger.success('Erased generated files successfully')
  }
}
